apiVersion: v1
kind: Pod
metadata:
  name: emptydir-pod
spec:
  restartPolicy: OnFailure
  containers:
    - name: rediscontainer
      image: redis
      volumeMounts:
        - name: redis-storage
          mountPath: /data/redis
  volumes:
    - name: redis-storage
      emptyDir: {}