apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  volumes:
    - name: hostpath-vol
      hostPath:
        path: /var/tmp
  restartPolicy: OnFailure
  containers:
    - name: hostpath-container
      image: alpine
      command: ["sleep", "3600"]
      volumeMounts:
        - name: hostpath-vol
          mountPath: /output