apiVersion: v1
kind: Pod
metadata:
  name: shared-volume-multicontainer-pod
spec:
  volumes:
    - name: html
      emptyDir: {}
  containers:
    - name: nginxcontainer
      image: nginx
      volumeMounts:
        - name: html
          mountPath: usr/share/nginx/html
      ports:
        - protocol: TCP
          containerPort: 80
    - name: alpinecontainer
      image: alpine
      volumeMounts:
        - name: html
          mountPath: /html
      command:
        - /bin/sh
        - '-c'
      args:
        - while true; do date >> /html/index.html; sleep 5; done
---
apiVersion: v1
kind: Service
metadata:
  name: shared-volume-service
spec:
  type: NodePort
  selector:
    name: shared-volume-multicontainer-pod
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 21600
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30100