apiVersion: v1
kind: Pod
metadata:
  name: jenkinspod
  labels:
    app: jenkins
spec:
  containers:
    - name: jenkinscontainer
      image: jenkins/jenkins:lts
      ports:
        - name: jenkinsport
          containerPort: 8080