apiVersion: v1
kind: Pod
metadata:
  name: lifecyclehooksdemopod
spec:
  containers:
    - name: nginx-demo
      image: nginx
      lifecycle:
        postStart:
          exec:
            command: ["/bin/sh", "-c", "echo In Post Start lifecycle event > /usr/share/nginx/html/index.html"]
        preStop:
          exec:
            command: ["/bin/sh", "-c", "nginx -s quit; while killall -0 nginx; do sleep 1; done"]