apiVersion: v1
kind: Pod
metadata:
  name: soft-node-affinity-pod-1
spec:
  containers:
    - name: app
      image: alpine
      command: ["sleep", "3600"]
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: disktype
              operator: In
              values:
                - ssd
---
apiVersion: v1
kind: Pod
metadata:
  name: soft-node-affinity-pod-2
spec:
  containers:
    - name: app
      image: alpine
      command: ["sleep", "3600"]
      resources:
        requests:
          memory: "64Mi"
          cpu: "1500m"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: disktype
              operator: In
              values:
                - ssd
---
apiVersion: v1
kind: Pod
metadata:
  name: preferred-node-affinity-pod
spec:
  containers:
    - name: app
      image: alpine
      command: ["sleep", "3600"]
      resources:
        requests:
          memory: "64Mi"
          cpu: "1000m"
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: disktype
                operator: In
                values:
                  - ssd
---
apiVersion: v1
kind: Pod
metadata:
  name: node-anti-affinity-pod
spec:
  containers:
    - name: app
      image: alpine
      command: ["sleep", "3600"]
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: disktype
              operator: NotIn
              values:
                - ssd